package UserInterface;

import LogicAndClasses.Account;
import LogicAndClasses.Customer;
import LogicAndClasses.Logic;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan Laabs
 */

// Singleton class, because there should only ever be one instance
public class CustomerSearch extends javax.swing.JFrame {

    private static CustomerSearch instance = null;
    private final Logic LOGIC;
    private Customer customer;
    private Account account;
    private ArrayList<Customer> customers = new ArrayList<>();
    
    private CustomerSearch() {
        this.LOGIC = Logic.getInstance();
        this.setTitle("Search for Customers");
        initComponents();
        cbxCriteria.addItem("Customer name");
        cbxCriteria.addItem("Customer ID");
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                onExit();
            }
        });
    }
    
    public void onExit() {
        resetAllFields();
        this.dispose();
    }
    
    public static CustomerSearch getInstance() {
        if(instance == null) {
            instance = new CustomerSearch();
        }
        return instance;
    }
    
    public void resetAllFields() {
        txfCriteria.setText("");
        txfCustomerID.setText("");
        txfCustomerName.setText("");
        cbxCustomerList.removeAllItems();
        
        btnEditCustomer.setEnabled(false);
        btnAddAccount.setEnabled(false);
        btnShowAccounts.setEnabled(false);
        cbxCustomerList.setEnabled(false);
    }
    
    public void setFields() {
        txfCustomerID.setText(Integer.toString(this.customer.getCUSTOMER_ID()));
        txfCustomerName.setText(this.customer.getFirstName() + " " + this.customer.getLastName());
        btnEditCustomer.setEnabled(true);
        btnAddAccount.setEnabled(true);
        btnShowAccounts.setEnabled(true);
    }
    
    public void refreshCustomerList() {
        cbxCustomerList.removeAllItems();
        cbxCustomerList.setEnabled(true);
        for (Customer c : this.customers) {
            cbxCustomerList.addItem(c.getFullName());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSearch = new javax.swing.JLabel();
        lblSearchFor = new javax.swing.JLabel();
        cbxCriteria = new javax.swing.JComboBox<>();
        txfCriteria = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblCustomerID = new javax.swing.JLabel();
        txfCustomerID = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        txfCustomerName = new javax.swing.JTextField();
        btnEditCustomer = new javax.swing.JButton();
        btnAddAccount = new javax.swing.JButton();
        btnShowAccounts = new javax.swing.JButton();
        cbxCustomerList = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setText("Search for customers");

        lblSearchFor.setText("Search for");

        cbxCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCriteriaActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblCustomerID.setText("Customer-ID");

        txfCustomerID.setEnabled(false);

        lblCustomerName.setText("Name of customer");

        txfCustomerName.setEnabled(false);

        btnEditCustomer.setText("Edit Customer");
        btnEditCustomer.setEnabled(false);
        btnEditCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustomerActionPerformed(evt);
            }
        });

        btnAddAccount.setText("Add new Account");
        btnAddAccount.setEnabled(false);
        btnAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccountActionPerformed(evt);
            }
        });

        btnShowAccounts.setText("Show Customer Accounts");
        btnShowAccounts.setEnabled(false);
        btnShowAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAccountsActionPerformed(evt);
            }
        });

        cbxCustomerList.setEnabled(false);
        cbxCustomerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCustomerListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSearchFor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbxCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cbxCustomerList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(txfCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAddAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearch)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchFor)
                    .addComponent(cbxCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbxCustomerList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddAccount))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerID)
                            .addComponent(txfCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerName)
                            .addComponent(txfCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnShowAccounts)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            String input = this.txfCriteria.getText();
            
            if (cbxCriteria.getSelectedIndex() == 0) {
                this.customers = LOGIC.findCustomersByName(input);
                this.customer = this.customers.get(0);
                setFields();
                refreshCustomerList();
            } else if (cbxCriteria.getSelectedIndex() == 1) {
                LOGIC.validateNumber(input, "customer ID");
                Customer c = LOGIC.findCustomerById(Integer.parseInt(input));
                this.customer = c;
                setFields();
            } 
        }
        catch (Exception e) {
            this.customer = null;
            this.customers = null;
            resetAllFields();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cbxCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCriteriaActionPerformed
        resetAllFields();
    }//GEN-LAST:event_cbxCriteriaActionPerformed

    private void btnAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccountActionPerformed
        if (LOGIC.isEditable()) {
            new CreateAccount(this.customer).setVisible(true);
            resetAllFields();
            LOGIC.setEditable(false);
            this.dispose();
            return;
        }
        JOptionPane.showMessageDialog(null, "Please close other editing dialogs first", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnAddAccountActionPerformed

    private void btnEditCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustomerActionPerformed
        if (LOGIC.isEditable()) {
            new EditCustomer(this.customer).setVisible(true);
            resetAllFields();
            LOGIC.setEditable(false);
            this.dispose();
            return;
        }
        JOptionPane.showMessageDialog(null, "Please close other editing dialogs first", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnEditCustomerActionPerformed

    private void cbxCustomerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCustomerListActionPerformed
        if (this.customers != null && cbxCustomerList.getSelectedIndex() != -1) {
            this.customer = this.customers.get(cbxCustomerList.getSelectedIndex());
            setFields();
        }
    }//GEN-LAST:event_cbxCustomerListActionPerformed

    private void btnShowAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAccountsActionPerformed
        if (LOGIC.isEditable()) {
            if (this.customer.getACCOUNTS().size() > 0) {
                new ShowAccounts(this.customer).setVisible(true);
                resetAllFields();
                this.dispose();
                return;
            }
            JOptionPane.showMessageDialog(null, "This customer has no account yet\nPlease create one first", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(null, "Please close other editing dialogs first", "Error", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnShowAccountsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnEditCustomer;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowAccounts;
    private javax.swing.JComboBox<String> cbxCriteria;
    private javax.swing.JComboBox<String> cbxCustomerList;
    private javax.swing.JLabel lblCustomerID;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearchFor;
    private javax.swing.JTextField txfCriteria;
    private javax.swing.JTextField txfCustomerID;
    private javax.swing.JTextField txfCustomerName;
    // End of variables declaration//GEN-END:variables
}
